const CartActionTypes = {
  TOGGLE_CART_HIDDEN: "TOGGLE_CART_HIDDEN",
  ADD_ITEM: "ADD_ITEM",
  CLEAR_ITEN_FROM_CART: "CLEAR_ITEN_FROM_CART",
  REMOVE_ITEM: "REMOVE_ITEM",
  CLEAR_ALL_ITEMS_FROM_CART: "CLEAR_ALL_ITEMS_FROM_CART"
};

export default CartActionTypes;
